### PR TITLE
Wen's dad joke

### PR DESCRIPTION
**Pull request by wzhang2705**

### CODE REVIEW

**Review by dunja-tomic — CHANGES_REQUESTED** [review]
Hmm I think you did something a little funky here - looks like you created a new html file instead of editing the current `README.md` file. You can either fix this in another commit, or tbh it might just be easier to close this PR and start fresh. Lmk if you want to go through this together!

(Great dad joke btw)

**Comment by wzhang2705** [comment]
I'm not sure why it was creating an html file. I deleted the html file and I made the changes in the md file, now.

**Review by vipj — APPROVED** [review]
Great joke

**Review by kyleyarwood — APPROVED** [review]
Good joke haha

**Comment by dunja-tomic** [comment]
Looks good to merge! Great job :)

**Review by dunja-tomic — APPROVED** [review]

**Pull request merged**
